# Generated by Django 3.2.5 on 2021-08-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='enter username', max_length=500, verbose_name='Usename')),
                ('email', models.EmailField(help_text='enter email', max_length=500, verbose_name='Email')),
                ('address', models.CharField(help_text='enter address', max_length=500, verbose_name='Address')),
            ],
        ),
    ]
